include: package:effective_dart/analysis_options.1.3.0.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_classes_with_only_static_members: false
    avoid_setters_without_getters: false
    avoid_lines_longer_than_80_chars: false